# Generated by Django 5.2 on 2025-05-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_cartitem_product_delete_catalogitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='discounted_price',
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
            preserve_default=False,
        ),
    ]
