# Generated by Django 5.2 on 2025-04-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('Business_name', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('mobile', models.IntegerField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='resume_image',
            field=models.ImageField(upload_to='resumes/'),
        ),
    ]
